### ISSUE TITLE
About Costs & Cost Calculator

### ISSUE THREAD

**Issue by evrend** [firevel/firevel#31]
Hello,
Firstly, thanks for creating such a good solution for Laravel serverless running.

I'm searching for a price/performance solution for serverless with PHP. We had tried AWS Lamda with Laravel|Lumen & [Php Bref](https://bref.sh/docs/). It's working but [caching](https://aws.amazon.com/elasticache/pricing/) and [rds database](https://aws.amazon.com/rds/aurora/pricing) not efficient in terms of price/performance. Same at serverless NoSQL/DynamoDB. It's looking cheap but If you use a query with little big data(1m+) then reading is starting to be costly.

As a result, your solution seems to a good solution for all needs with PHP serverless|Laravel Serverless. And it's a good price/performance solution. If you can build a cost calculator about Firevel cost for GCloud services, it will be excellent for Firevel users. Of course, and for me. I'm an AWS user, therefore I can't exactly calculate the cost for GCloud.
Example calculator
https://cost-calculator.bref.should

Just out of curiosity, Why didn't you use Firebase Authentication? It can implement simple and It's a good price/performance solution for authentication.
https://medium.com/@morrislaptop/laravel-firebase-auth-cff892b116a2

**Comment by sl0wik** [comment]
Firevel is built with 100% serverless approach, where you need no rds, or redis for caching. I'm running it on production with no servers at all. I will consider making some calculator.

Firevel got authentication library https://github.com/firevel/firebase-authentication and I'm using it all the time. It's not implemented by default because it's unclear how to handle users created on Firebase side. There are multiple ways to handle it and I'm not convinced which one would be the best by default.
